name = "minterr"
type = "webpack"
account_id = "792461088a4c863230f3faee467094b1"
# workers_dev = true
route = "minterr.org/*"
zone_id = "cbbc31f806ffcbb48c4dcdef7bd07133"

[site]
bucket = "../public"
entry-point = "workers-site"
